### ISSUE TITLE
About SFull

### ISSUE THREAD

**Issue by helena-lena** [cambridgeltl/mop#2]
Hi, thanks for sharing your great work:)
In the kg_dir file, there is no difference between S20Rel and SFull.
I think SFull is equivalent to S20Rel because SFull "relation2id.txt" file contains 20 relations.
Could you please provide the SFull file?

**Comment by mengzaiqiao** [comment]
Hi, the SFull file is now uploaded in the zip file. Thanks for pointing out this.

**Comment by helena-lena** [comment]
Thank you for your response!
